config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :bookings, only: %i[index]
  resources :products do
    resources :bookings
    collection do
      get :my_products
    end
  end
  root to: "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :product
  belongs_to :user

  validates :start_date, :finish_date, presence: true
  validates :finish_date, comparison: { greater_than: :start_date }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :description, presence: true
  validates :description, uniqueness: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many_attached :photos

  validates :title, :description, :price, :category_id, presence: true
  validates :title, length: { in: 6..30 }
  validates :description, length: { in: 10..1000, wrong_length: "La descripción debe tener entre 10 y 1000 caracteres" }

  include PgSearch::Model
  pg_search_scope :search_products,
    against: [ :title, :color, :size, :price, :brand,:gender ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products, through: :bookings, dependent: :destroy
  has_many :bookings, dependent: :destroy, through: :products

  validates :username, :first_name, :last_name, :phone_number, :address, presence: true
  validates :username, uniqueness: true
  validates :username, length: { in: 6..30 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, :phone_number, :address, :avatar_url])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username, :phone_number, :address, :avatar_url])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_user, only: %i[new create edit update destroy]
  before_action :set_product, only: %i[new create show edit update destroy]
  before_action :set_booking, only: %i[edit update destroy]

  def index
    @bookings = policy_scope(Booking)
  end

  def new
    @booking = Booking.new
    authorize @booking
  end

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user_id = @user.id
    @booking.product_id = @product.id
    @booking.status = "pendiente"
    if @booking.save
      redirect_to bookings_path
    else
      render :new, status: :unprocessable_entity
    end
    authorize @booking
  end

  def edit
    authorize @booking
  end

  def update
    @booking.update(status: params[:status]) if params[:status].present?
    if @booking.save
      redirect_to bookings_path
    else
      render :new, status: :unprocessable_entity
    end
    authorize @booking
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path
    authorize @booking
    # el authorize tiene un problema entre el booking y el product
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :finish_date)
  end

  def set_product
    @product = Product.find(params[:product_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_user
    @user = current_user
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @products = Product.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_user, only: %i[new create edit update destroy my_products]
  before_action :set_product, only: %i[show edit update destroy]

  def index
    # @products = Product.all
    @products = policy_scope(Product)
  end

  def my_products
    authorize Product
    @products = Product.where(user_id: @user)
  end

  def new
    @product = Product.new
    authorize @product
  end

  def show
    authorize @product
  end

  def create
    @product = Product.new(product_params)
    @product.user = @user
    if @product.save
      redirect_to products_path
    else
      render :new, status: :unprocessable_entity
    end
    authorize @product
  end

  def edit
    authorize @product
  end

  def update
    authorize @product
    if @product.update(product_params)
    redirect_to products_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @product
    @product.destroy
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :color, :size, :price, :brand, :images_url, :gender, :category_id, photos: [])
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def set_user
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_booking_cards.html.erb
<div class="container" data-controller="bookings">
  <div class="row">
    <h2 class="text-uppercase">Reservas Recibidas</h2>
      <% @bookings.where.not(user: current_user).each do |booking| %>
        <div class="offset-2 col-8 col-sm-8 col-lg-8">
          <div class="card-product m-3">
            <%= cl_image_tag booking.product.photos.first.key, height: 300, width: 400, crop: :fill %>
            <div class="card-product-infos">
              <div class="d-flex w-100">
                <h5 class="text-uppercase"><%= booking.product.title %></h5>
              </div>
              <p>Reservado por <%= booking.user.username %></h5>
              <p class="text-capitalize"><%= booking.product.description %></p>
              <p>$<%= '%.0f' % booking.product.price %> x día</p>
              <div>
                <p>Desde: <%= booking.start_date %> Hasta: <%= booking.finish_date %></p>
                <p>Cantidad de Días: <%= (booking.finish_date - booking.start_date).to_i %></p>
                <p class="card-price">$<%= number_with_precision(((booking.finish_date - booking.start_date).to_i *  booking.product.price), :precision => 0, :delimiter => ',') %></p>
                <% unless booking.status == "pendiente"  %>
                  <div class="status-option">
                    <p><span class="text-uppercase">
                      <%= '<i class="fas fa-check-circle text-success"></i>'.html_safe if booking.status == "aceptado" %>
                      <%= '<i class="fas fa-times-circle text-danger"></i>'.html_safe if booking.status == "rechazado" %>
                    </span></p>
                  </div>
                <% else %>
                  <div class="d-flex p-1 status-option">
                    <%= button_to '<i class="fa-solid fa-check"></i>'.html_safe, product_booking_path(booking.product_id, booking, status: "aceptado"), remote: true, class:"btn btn-success m-1", method: :patch %>
                    <%= button_to '<i class="fa-solid fa-xmark"></i>'.html_safe, product_booking_path(booking.product_id, booking, status: "rechazado"), remote: true, class:"btn btn-danger m-1", method: :patch %>
                  </div>
                <% end %>
                <%= link_to '<i class="fa fa-trash"></i>'.html_safe, product_booking_path(booking.product_id, booking), class:"btn btn-primary", data: {turbo_method: :delete, turbo_confirm: "Seguro?"} if booking.user == current_user %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
  </div>
  <div class="row">
    <h2 class="text-uppercase">Mis Reservas</h2>
      <% @bookings.where(user: current_user).each do |booking| %>
        <div class="offset-2 col-8 col-sm-8 col-lg-8">
          <div class="card-product m-3">
            <%= cl_image_tag booking.product.photos.first.key, height: 300, width: 400, crop: :fill %>
            <div class="card-product-infos">
              <div class="status-option">
                <p><span class="text-uppercase">
                  <%= '<i class="fas fa-check-circle text-success"></i>'.html_safe if booking.status == "aceptado" %>
                  <%= '<i class="fas fa-times-circle text-danger"></i>'.html_safe if booking.status == "rechazado" %>
                  <%= '<i class="fas fa-clock text-warning"></i>'.html_safe if booking.status == "pendiente" %>
                </span></p>
              </div>
              <h5 class="text-uppercase"><%= booking.product.title %></h5>
              <p class="text-capitalize"><%= booking.product.description %></p>
              <p>$<%= '%.0f' %  booking.product.price %> x día</p>
              <div>
                <p>Desde: <%= booking.start_date %> Hasta: <%= booking.finish_date %></p>
                <p>Cantidad de Días: <%= (booking.finish_date - booking.start_date).to_i %></p>
                <p class="card-price">$<%= number_with_precision(((booking.finish_date - booking.start_date).to_i *  booking.product.price), :precision => 0, :delimiter => ',') %></p>
                <%= link_to '<i class="fa fa-trash"></i>'.html_safe, product_booking_path(booking.product_id, booking), class:"btn btn-primary", data: {turbo_method: :delete, turbo_confirm: "Seguro?"} %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/bookings/_booking_form.html.erb
<%= simple_form_for [@product, @booking] do |f| %>
  <%= f.input :start_date, label: "Fecha de Inicio" %>
  <%= f.input :finish_date, label: "Fecha de Fin" %>
  <%= f.submit "Realizar Reserva", class: "btn btn-primary float-end" %>
<% end %>

app/views/bookings/edit.html.erb
<%= simple_form_for [@product, @booking] do |f| %>
  <%= f.input :start_date %>
  <%= f.input :finish_date %>
  <%= f.submit "Actualizar Reserva", class: "btn btn-primary" %>
<% end %>

app/views/bookings/index.html.erb
<div class="container">
  <div class="row">
    <%= render "booking_cards" %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="row">
    <div class="offset-2 col-8 col-sm-8 col-lg-8">
      <div class="card-product m-3">
        <%= cl_image_tag @product.photos.first.key, height: 300, width: 400, crop: :fill %>
        <div class="card-product-infos">
          <h5 class="text-uppercase"><%= @product.title %></h5>
          <p class="text-capitalize"><%= @product.description %></p>
          <p>$<%= '%.0f' % @product.price %> x día</p>
          <p> Producto de <%= @product.user.username %></p>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <h3 class="text-uppercase text-center mt-4">Reserva el producto elijiendo las fechas en que lo necesitas</h3>
    <div class="offset-3 col-6">
      <%= render "booking_form" %>
    </div>
  </div>
</div>

app/views/bookings/new_html.erb
<%= render "booking_form" %>

app/views/bookings/show.html.erb
<div class="container">
  <div class="row">
    <div class="offset-2 col-8 col-sm-8 col-lg-8">
      <div class="card-product m-3">
        <%= cl_image_tag @booking.product.photos.first.key, height: 300, width: 400, crop: :fill %>
        <div class="card-product-infos">
          <h4>Reserva hecha por <%= @booking.user.username %></h5>
          <h5 class="text-uppercase"><%= @booking.product.title %></h5>
          <p class="text-capitalize"><%= @booking.product.description %></p>
          <p>$<%= @booking.product.price %> x día</p>
          <div>
            <p>Desde: <%= @booking.start_date %> Hasta: <%= @booking.finish_date %></p>
            <p>Cantidad de Días: <%= @booking.finish_date - @booking.start_date %></p>
            <p class="card-price">Monto Total: $<%= (@booking.finish_date - @booking.start_date).to_i *  @booking.product.price %></p>
            <% if @booking.status == "pendiente"  %>
              <p>Estado de la Reserva: Pendiente de Respuesta</p>
            <% else %>
              <p class="btn btn-success"><i class="fa-solid fa-check"></i></p>
              <p class="btn btn-danger"><i class="fa-solid fa-xmark"></i></p>
            <% end %>
            <%= link_to '<i class="fa fa-trash"></i>'.html_safe, product_booking_path(@booking.product_id, @booking), class:"btn btn-primary", data: {turbo_method: :delete, turbo_confirm: "Seguro?"} %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LookAtMe</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path("logos/logo_square.png") %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
      <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path('banners/banner-blurred.jpg') %>);">
    <div class="content center-column offset-2">
      <h1 class="text-uppercase">Look at Me</h1>
      <h2 class="text-light mb-3">Tu armario infinito</h2>
      <%= link_to "Registrate", new_user_registration_path, class: "btn btn-primary fs-4 fw-bold font-monospace rounded-pill mt-3" if !current_user %>
      <%= link_to "Reserva tu Prenda", new_user_registration_path, class: "btn btn-primary fs-4 fw-bold font-monospace rounded-pill mt-3" if current_user %>
      <p><span data-controller="typed-js"></span></p>
    </div>
</div>

<div class="cards my-3">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.8)), url(<%= image_path('banners/banner_feature_choice.jpg') %>)">
    <div class="text-center">
      <h4>ELIGE</h4>
      <p>Selecciona la fecha y las prendas que quieres elegir</p>
    </div>
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.8)), url(<%= image_path('banners/banner_feature_disfruta.jpg') %>)">
    <div class="text-center">
      <h4>DISFRUTA</h4>
      <p>Viste las mejores prendas como si fueran tuyas</p>
    </div>
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.8)), url(<%= image_path('banners/banner_feature_coordinar.jpg') %>)">
    <div class="text-center">
      <h4>DEVUELVE</h4>
      <p>Coordina con el dueño como regresarás tu pedido</p>
    </div>
  </div>
</div>
<h4 class="my-4 offset-4">Ultimas incorporaciones a nuestro placard</h4>

<div class="container">
  <%= render "shared/product_card" %>
</div>

app/views/products/edit.html.erb
<div class="text-uppercase justify-content-center bg-dark d-flex align-items-center" style="height: 200px; color: white; font-size: 1.8em;">
  <h1 style="">Editar Producto</h1>
</div>
<div class="container offset-3 col-6">
  <div >
    <%= render "shared/product_form" %>
  </div>
</div>

app/views/products/index.html.erb
<div class="text-uppercase justify-content-center bg-dark d-flex align-items-center" style="height: 200px; color: white; font-size: 1.8em;">
  <h1 style="">Placard</h1>
</div>
<div class="container">
  <div class="row">
    <%= render "shared/product_card_index" %>
  </div>
</div>

app/views/products/my_products.html.erb
<div class="text-uppercase justify-content-center bg-dark d-flex align-items-center" style="height: 200px; color: white; font-size: 1.8em;">
  <h1 style="">Mis Productos</h1>
</div>
<div class="container">
  <div class="row">
    <%= render "shared/product_card_index" %>
  </div>
</div>

app/views/products/new.html.erb
<div class="text-uppercase justify-content-center bg-dark d-flex align-items-center mb-4" style="height: 200px; color: white; font-size: 1.8em;">
  <h1>Nuevo Producto</h1>
</div>
<div class="container offset-3 col-6">
  <div class="form-inputs w-50">
    <%= render "shared/product_form" %>
  </div>
</div>

app/views/products/show.html.erb
<div class="container">
  <div class="row productfotocard mt-4">
    <div class="offset-1 col-5">
            <div class="product-image">
              <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <%=cl_image_tag @product.photos.first.key, crop: :fill, class:"show-foto"%>
                  </div>
                  <div class="carousel-item">
                    <%=cl_image_tag @product.photos.last.key, crop: :fill, class:"show-foto" %>
                  </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </button>
              </div>
            </div>
    </div>
    <div class= "col-5">
      <div class="card-product-show">
          <div class="m-3 p-4">
              <h1 class="text-uppercase mb-4 text-center"><%= @product.title%></h1>
            <div class="card-product-infos">
              <p class="text-capitalize"><%= @product.description %></p>
              <p class="text-capitalize"><%= @product.category.description + " - " + @product.gender %></p>

              <ul class="list-group list-group-flush my-5">
                <li class="list-group-item"><i class="far fa-copyright"></i>   Marca: <%= @product.brand %></li>
                <li class="list-group-item"><i class="fas fa-palette"></i>   Color: <%= @product.color %></li>
                <li class="list-group-item"><i class="fas fa-ruler-horizontal"></i>   Talle: <%= @product.size %></li>
                <li class="list-group-item"><i class="fas fa-venus-mars"></i></i>   Genero: <%= @product.gender %></li>
                <li class="list-group-item"><i class="fas fa-user"></i>   Usuario: <%= @product.user.username %></li>
                <li class="list-group-item">$ <%= number_with_precision(@product.price, :precision => 0, :delimiter => ',') %></li>

              </ul>
            </div>
            <div class="d-flex justify-content-around">
              <%= link_to "Reservar", new_product_booking_path(@product), class:"btn btn-primary text-uppercase" if @product.user != current_user %>
              <%= link_to '<i class="fa-solid  fa-pen"></i>'.html_safe, edit_product_path(@product), class:"btn btn-primary mx-1" if @product.user == current_user %>
              <%= link_to '<i class="fa fa-trash"></i>'.html_safe, product_path(@product), class:"btn btn-primary", data: {turbo_method: :delete, turbo_confirm: "Seguro?"} if @product.user == current_user %>
              <%#= button_to "Destroy this produnct", @product, method: :delete if policy(@product).destroy? %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light sticky-top navbar-lewagon">
  <div class="container-fluid">
    <div class="">
      <%= link_to root_path, class: "navbar-brand d-flex" do %>
        <%= image_tag "logos/logo_square.png" %>
        <p class="brand mx-2">Look at Me</p>
      <% end %>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Placard", products_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Nuevo Producto", new_product_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Inicio", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag current_user.avatar_url? ? current_user.avatar_url : "https://kitt.lewagon.com/placeholder/users/random"  , class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Reservas", bookings_path, class: "dropdown-item" %>
              <%= link_to "Mis Productos", my_products_products_path, class: "dropdown-item" %>
              <%= link_to "Mis Ventas", "#", class: "dropdown-item" %> <!-- Pendiente subir el path cuando este el controller de booking-->
              <%= link_to "Editar Usuario", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Desloguearse", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Loguearse/Registrarse", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_product_card.html.erb
<div class=“container”>
  <div class="row">
    <% @products.where.not(user: current_user).each do |product| %>
      <div class="col-md-3 col-sm-6 mt-3">
        <div class="product-grid p-4">
          <div class="product-image">
            <a href="<%=product_path(product)%>" class="image">
            <% if product.photos.first == nil%>
            <% else %>
                <%=cl_image_tag product.photos.first.key, height: 300, width: 400, crop: :fill, class:"img-1"%>
                <%=cl_image_tag product.photos.last.key, height: 300, width: 400, crop: :fill, class:"img-2"%>
              <% end %>
            </a>
            <ul class="product-links">
              <li><a href="#"><i class="fa fa-heart"></i></a></li>
              <li><a href="#"><i class="fa fa-random"></i></a></li>
              <li><a href="<%=new_product_booking_path(product)%>"><i class="fa fa-shopping-cart"></i></a></li>
            </ul>
            <a href="<%=product_path(product)%>" class="product-view"><i class="fa fa-search"></i></a>
          </div>
          <div class="product-content position-relative">
            <ul class="rating">
              <li class="fas fa-star"></li>
              <li class="fas fa-star"></li>
              <li class="fas fa-star"></li>
              <li class="fas fa-star"></li>
              <li class="fas fa-star disable"></li>
              <li class="disable">(1 reviews)</li>
            </ul>
            <h3 class="title">
              <%= link_to "#{product.title}", product_path(product)%>
            </h3>
            <p class="text-uppercase"><%= product.category.description + " - " + product.gender %></p>
            <p class="text-capitalize"><%= product.description %></p>
            <div>
              <%= link_to "Reservalo", new_product_booking_path(product), class:"btn btn-primary text-uppercase" %>
              <div class="price">$ <%= number_with_precision(product.price, :precision => 0, :delimiter => ',') %></div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_product_card_index.html.erb
<div class=“container”>
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-md-3 col-sm-6 mt-3">
        <div class="product-grid p-4">
          <div class="product-image">
            <a href="<%=product_path(product)%>" class="image">
            <% if product.photos.first == nil%>
            <% else %>
                <%=cl_image_tag product.photos.first.key, height: 300, width: 400, crop: :fill, class:"img-1"%>
                <%=cl_image_tag product.photos.last.key, height: 300, width: 400, crop: :fill, class:"img-2"%>
              <% end %>
            </a>
            <ul class="product-links">
              <li><a href="#"><i class="fa fa-heart"></i></a></li>
              <li><a href="#"><i class="fa fa-random"></i></a></li>
              <li><a href="<%=new_product_booking_path(product)%>"><i class="fa fa-shopping-cart"></i></a></li>
            </ul>
            <a href="<%=product_path(product)%>" class="product-view"><i class="fa fa-search"></i></a>
          </div>
          <div class="product-content position-relative">
            <ul class="rating">
              <li class="fas fa-star"></li>
              <li class="fas fa-star"></li>
              <li class="fas fa-star"></li>
              <li class="fas fa-star"></li>
              <li class="fas fa-star disable"></li>
              <li class="disable">(1 reviews)</li>
            </ul>
            <h3 class="title">
              <%= link_to "#{product.title}", product_path(product)%>
            </h3>
            <p class="text-capitalize"><%= product.description %></p>
            <p class="text-capitalize"><%= product.category.description + " - " + product.gender %></p>

            <ul class="list-group list-group-flush mb-3">

              <li class="list-group-item"><i class="far fa-copyright"></i>   Marca: <%= product.brand %></li>
              <li class="list-group-item"><i class="fas fa-palette"></i>   Color: <%= product.color %></li>
              <li class="list-group-item"><i class="fas fa-ruler-horizontal"></i>   Talle: <%= product.size %></li>
              <li class="list-group-item"><i class="fas fa-venus-mars"></i></i>   Genero: <%= product.gender %></li>
              <li class="list-group-item"><i class="fas fa-user"></i>   Usuario: <%= product.user.username %></li>

            </ul>
            <div>
              <%= link_to "Reservar", new_product_booking_path(product), class:"btn btn-primary text-uppercase" if product.user != current_user %>
              <%= link_to '<i class="fa-solid  fa-pen"></i>'.html_safe, edit_product_path(product), class:"btn btn-primary mx-1" if product.user == current_user %>
              <%= link_to '<i class="fa fa-trash"></i>'.html_safe, product_path(product), class:"btn btn-danger mx-1", data: {turbo_method: :delete, turbo_confirm: "Seguro?"} if product.user == current_user %>
              <div class="price">$ <%= number_with_precision(product.price, :precision => 0, :delimiter => ',') %></div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>